playground/django/ProTwo/AppTwo/urls.py
from django.conf.urls import url
from AppTwo import views

urlpatterns = [
    url('users',views.users, name='users'),
    url('', views.index, name='index'),
]

playground/django/ProTwo/ProTwo/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('apptwo/', include('AppTwo.urls')),
    path('first_app/', include('first_app.urls')),
    path('basic_app/', include('basic_app.urls')),
    path('admin/', admin.site.urls),
]

playground/django/ProTwo/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

# template tagging
app_name = 'basic_app'

urlpatterns = [
    url('other',views.other, name='other'),
    url('relative',views.relative, name='relative'),
    url('', views.index, name='index'),
]

playground/django/ProTwo/first_app/urls.py
from django.conf.urls import url
from first_app import views

urlpatterns = [
    url('form',views.form_name_view, name='users'),
    url('', views.index, name='index'),
]

playground/django/ProTwo/AppTwo/models.py
from django.db import models
# SuperUserInformation
# User: Jose
# Email: training@pieriandata.com
# Password: testpassword

# Create your models here.
class User(models.Model):
    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)
    email = models.EmailField(max_length=254,unique=True)

playground/django/ProTwo/basic_app/models.py
from django.db import models

# Create your models here.

playground/django/ProTwo/first_app/models.py
from django.db import models

class Topic(models.Model):
    top_name = models.CharField(max_length=264, unique=True)

    def __str__(self):
        return self.top_name

class Webpage(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length=264, unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name

class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage, on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return self.date

playground/django/ProTwo/AppTwo/forms.py
from django import forms
from AppTwo.models import User

class NewUserForm(forms.ModelForm):
    #custom validations here
    class Meta():
        model = User
        fields = "__all__"

playground/django/ProTwo/first_app/forms.py
from django import forms

class FormName(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    text = forms.CharField(widget=forms.Textarea)
    botcather = forms.CharField(required=False, widget=forms.HiddenInput)

    def clean_botcatcher(self):
        botcatcher = self.cleaned_data['botcatcher']
        if len(botcatcher) > 0:
            raise forms.ValidationError("Gotcha Bot!")
        return botcatcher

playground/django/ProTwo/AppTwo/views.py
from django.shortcuts import render
from django.http import HttpResponse
from AppTwo.forms import NewUserForm

def index(request):
    return render(request, 'AppTwo/index.html')

def users(request):
    form = NewUserForm()

    if request.method == 'POST':
        form = NewUserForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print('ERROR FORM INVALID')
        
    return render(request, 'AppTwo/users.html', {'form': form})

playground/django/ProTwo/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'hello world', 'number':100}
    return render(request, 'basic_app/index.html', context_dict)

def other(request):
    return render(request, 'basic_app/other.html')

def relative(request):
    return render(request, 'basic_app/relative_url_templates.html')

playground/django/ProTwo/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from first_app.models import Topic, Webpage, AccessRecord
from . import forms

def index(request):
    webpages_list = AccessRecord.objects.order_by('date')
    my_dict = {'access_records': webpages_list}
    return render(request, 'first_app/index.html', context=my_dict)

def form_name_view(request):
    form = forms.FormName()

    if request.method == 'POST':
        form = forms.FormName(request.POST)

        if form.is_valid():
            print("Validations success!")
        
        print("Name: ", form.cleaned_data['name'])
        print("Email: ", form.cleaned_data['email'])
        print('Text: ', form.cleaned_data['text'])

    return render(request, 'first_app/form_page.html', {'form':form})

playground/django/ProTwo/templates/basic_app/base.html
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'basic_app:index' %}">BRAND</a></li>
                <li><a class="nav-item nav-link" href="{% url 'basic_app:index' %}">Admin</a></li>
                <li><a class="nav-item nav-link" href="{% url 'basic_app:other' %}}">Other</a></li>
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block body_block %}
        <!-- Anything outside of this will be inherited if you extend! -->
        {% endblock %}
    </div>
</body>

</html>

playground/django/ProTwo/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}
    <h1>Welcome to index</h1>
    <h1>{{ text|upper }}</h1>
    <h1>{{ text|cut:'hello' }}</h1>
    <h1>{{ number|add:"99" }}</h1>
{% endblock %}

playground/django/ProTwo/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}
    <h1>Welcome to other</h1>
    <h2>This is an example of template inheritance!</h2>
{% endblock %}

playground/django/ProTwo/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Welcome to URL Templates</h1>
    <a href="{% url 'basic_app:other' %}">The other page</a>
    <a href="{% url 'admin:index' %}">Link to admin</a>
    <a href="{% url 'index' %}">Link to index</a>
</body>
</html>